version: "3.1"

services:

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: amicourses
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: amico
    container_name: mysql
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - back-tier

  amicourses:
    build:
      context: ./AMICOServer
    container_name: amicoursesWEB
    depends_on:
      - "mysql"
    ports:
      - "8080:8080" 
    networks:
      - back-tier
volumes:
  db-data:

networks:
  front-tier:
  back-tier:
